package com.abubakr.taskstreak.util

import com.abubakr.taskstreak.data.model.CategoryEntity
import com.abubakr.taskstreak.data.model.CompletionLogEntity
import com.abubakr.taskstreak.data.model.HabitChainEntity
import com.abubakr.taskstreak.data.model.SubtaskEntity
import com.abubakr.taskstreak.data.model.TaskEntity
import org.json.JSONArray
import org.json.JSONObject

object DesktopSyncBridge {
    /**
     * Generates a universal Desktop Companion schema JSON
     */
    fun exportForDesktop(
        tasks: List<TaskEntity>,
        subtasks: List<SubtaskEntity>,
        logs: List<CompletionLogEntity>,
        categories: List<CategoryEntity>,
        chains: List<HabitChainEntity>
    ): String {
        val root = JSONObject()
        root.put("schemaVersion", 2)
        root.put("sourcePlatform", "Android")
        root.put("exportedAt", System.currentTimeMillis())
        root.put("formattedDate", DateUtils.todayString())

        // Categories
        val catsArray = JSONArray()
        categories.forEach { c ->
            val obj = JSONObject()
            obj.put("id", c.id)
            obj.put("name", c.name)
            obj.put("colorHex", c.colorHex)
            catsArray.put(obj)
        }
        root.put("categories", catsArray)

        // Tasks
        val tasksArray = JSONArray()
        tasks.forEach { t ->
            val obj = JSONObject()
            obj.put("id", t.id)
            obj.put("title", t.title)
            obj.put("category", t.category)
            obj.put("categoryColorHex", t.categoryColorHex)
            obj.put("recurrenceType", t.recurrenceType)
            obj.put("customDaysOfWeek", t.customDaysOfWeek)
            obj.put("startDate", t.startDate)
            obj.put("endDate", t.endDate)
            obj.put("reminderTime", t.reminderTime)
            obj.put("note", t.note)
            obj.put("isHabit", t.isHabit)
            obj.put("pomodoroCount", t.pomodoroCount)
            tasksArray.put(obj)
        }
        root.put("tasks", tasksArray)

        // Subtasks
        val subtasksArray = JSONArray()
        subtasks.forEach { s ->
            val obj = JSONObject()
            obj.put("id", s.id)
            obj.put("taskId", s.taskId)
            obj.put("title", s.title)
            obj.put("isCompleted", s.isCompleted)
            subtasksArray.put(obj)
        }
        root.put("subtasks", subtasksArray)

        // Completion Logs
        val logsArray = JSONArray()
        logs.forEach { l ->
            val obj = JSONObject()
            obj.put("taskId", l.taskId)
            obj.put("date", l.date)
            obj.put("completedAt", l.completedAt)
            logsArray.put(obj)
        }
        root.put("completionLogs", logsArray)

        // Habit Chains
        val chainsArray = JSONArray()
        chains.forEach { ch ->
            val obj = JSONObject()
            obj.put("id", ch.id)
            obj.put("title", ch.title)
            obj.put("taskIds", ch.taskIds)
            obj.put("bonusXp", ch.bonusXp)
            chainsArray.put(obj)
        }
        root.put("habitChains", chainsArray)

        return root.toString(2)
    }

    /**
     * Generates a Markdown checklist export suitable for desktop notes (Obsidian, Notion, Markdown files)
     */
    fun exportToMarkdown(tasks: List<TaskEntity>, date: String = DateUtils.todayString()): String {
        val sb = StringBuilder()
        sb.appendLine("# 📋 Task Streak Tracker - Export ($date)")
        sb.appendLine()
        sb.appendLine("## Active Habits & Tasks")
        tasks.filter { !it.isArchived }.forEach { task ->
            val type = if (task.isHabit) "🔥 [Habit]" else "✓ [Task]"
            val reminder = task.reminderTime?.let { " ⏰ $it" } ?: ""
            sb.appendLine("- [ ] **${task.title}** ($type - ${task.category}$reminder)")
            if (!task.note.isNullOrBlank()) {
                sb.appendLine("  > ${task.note}")
            }
        }
        sb.appendLine()
        sb.appendLine("---")
        sb.appendLine("*Generated by Task Streak Tracker for Desktop Companion*")
        return sb.toString()
    }
}
